[theme]
primaryColor="#A6609C"
backgroundColor="#FAF2FA"
secondaryBackgroundColor="#BAA8BA"
textColor="#000000"
font = "monospace"
codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
